from pathlib import Path
import re

ROOT=Path(__file__).resolve().parents[1]
html=(ROOT/'app/src/main/assets/index.html').read_text(encoding='utf-8')

ids=re.findall(r'id=["\']([^"\']+)',html)
seen=set(); dup=[]
for ident in ids:
    if ident in seen: dup.append(ident)
    seen.add(ident)
assert not dup, 'Duplicate DOM ids: '+', '.join(sorted(set(dup)))

# One canonical preparation shell and one final controller.
assert html.count('id="cpFinalShell"')==1
assert html.count('id="cp-final-interaction-controller"')==1
assert html.count('id="cp-ui-runtime-v115"')==0

# Six, and only six, preparation shortcuts.
assert html.count('data-cp-detail=')==6
for kind in ('route','audio','orientation','pause','support','notes'):
    assert html.count(f'data-cp-detail="{kind}"')==1,kind

# The visible preparation must not reuse or move the old configuration cards.
assert 'detail.appendChild' not in html
assert 'openConfig(kind)' not in html
assert 'cp-legacy-prep-card' in html
assert '#functionGrid{display:none!important}' in html

# A runtime modal is created once; legacy cards remain hidden source controls.
assert "modal.id='cpConfigModal'" in html
assert 'function show(kind)' in html
assert 'function closeModal()' in html

# No duplicate global preparation menu is generated by a legacy runtime.
assert 'id="cpMenuPanel"' not in html or html.count('id="cpMenuPanel"')==1

print('No-duplicate-UI regression: OK')